spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-boot-synchronized-test
    username: postgres
    password: time0418
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
